### ISSUE TITLE
Data mining tool to collect contest results

### ISSUE THREAD

**Issue by crazy4pi314** [unitaryfoundation/unitaryhack2021#23]
I have been working on a strategy for collecting/logging the hackathon results, but could use some help.

The basic idea is to use the GitHub API to do advanced searches for the `[unitaryhack]` string in the title of PRs on participating repos. I can do this on the [advanced search page manually](https://github.com/search/advanced?q=unitaryHACK&type=Repositories) but I would love some automation for this via say a Python script, with a stretch goal to embed this on the [event website](hack2021.unitary.fund).

Some resources I was looking at:
- https://codesnippet.io/github-api-tutorial/
- https://docs.microsoft.com/en-us/azure/azure-functions/create-first-function-vs-code-python

**Comment by crazy4pi314** [comment]
Thanks to @yusharth for volunteering to help out with this!! 🎉 Please drop any questions/ideas/discussion here as needed :)

**Comment by crazy4pi314** [comment]
@yusharth, do you have any updates/are you stuck on anything?

**Comment by yusharth** [comment]
Still working on it. Sorry, I wasn't able give time in past few days.

**Comment by crazy4pi314** [comment]
Resolved with the new GH action on this repo.
