### ISSUE TITLE
Consider adding a countdown timer to website

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfoundation/unitaryhack2021#33]
It may be nice to have a countdown on the website, e.g., showing how many [days, hours, minutes, minute] are left to [start, finish] of Unitary Hack. 

It should be fairly easy to script it even in python, I'm not sure about how this can show up in the website or if there are some fancy pre-built ones like with cyberpunk / hacking felling or so.

**Comment by a6you** [comment]
Hello, I'm Austin! I saw this issue on goodfirstissues.com and I thought it might be interesting to tackle. I'm fairly new to web development and trying to learn by looking at some open source projects. Is this an issue I can work on, and if so, is there anything I should be careful of or guidance you can give me?
